/* Service worker — generated by build.js, do not edit sw.js by hand.

   Two strategies, on purpose:

   - The PAGE (any navigation) is network-first with a short timeout. The whole
     game is one HTML file, so this is what decides whether a new build shows up
     the moment you open it or only the launch after. Cache-first was making
     every deploy invisible until the second start.
   - EVERYTHING ELSE (icons, manifest) stays cache-first: those never change
     without the page changing too, and they must be instant.

   The timeout is what keeps the tablet usable on bad wifi: if the network has
   not answered in NAV_TIMEOUT we serve the cached game and let the download
   finish in the background, so the next launch is fresh. A child must never sit
   in front of a white screen because the router is having a bad day. */
var CACHE = 'dino-stazione-cb530c59b6';
var NAV_TIMEOUT = 2500;
var SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon.svg',
  './icon-180.png',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE)
      .then(function (c) { return Promise.allSettled(SHELL.map(function (u) { return c.add(u); })); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys()
      .then(function (keys) {
        return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
      })
      .then(function () { return self.clients.claim(); })
  );
});

function isNavigation(req) {
  return req.mode === 'navigate' || req.destination === 'document';
}

/* The cached game, whatever URL was asked for: '/' and '/index.html' are the
   same document and either may be what got cached. */
function cachedPage(req) {
  return caches.match(req, { ignoreSearch: true }).then(function (hit) {
    return hit || caches.match('./index.html', { ignoreSearch: true });
  });
}

function store(req, res) {
  if (!res || !res.ok) return;
  var copy = res.clone();
  caches.open(CACHE).then(function (c) { c.put(req, copy); }).catch(function () {});
}

function navigate(req) {
  return new Promise(function (resolve) {
    var settled = false;
    var timer = setTimeout(function () {
      if (settled) return;
      // Network is slow: hand over the cached game now. The fetch below is
      // still running and will refresh the cache for next time.
      cachedPage(req).then(function (hit) {
        if (settled || !hit) return;      // no cache yet: wait for the network
        settled = true;
        resolve(hit);
      });
    }, NAV_TIMEOUT);

    fetch(req).then(function (res) {
      clearTimeout(timer);
      store(req, res);
      if (settled) return;
      settled = true;
      resolve(res);
    }).catch(function () {
      clearTimeout(timer);
      if (settled) return;
      cachedPage(req).then(function (hit) {
        if (settled) return;
        settled = true;
        resolve(hit || Response.error());
      });
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;            // cloud sync goes straight to the network

  if (isNavigation(req)) { e.respondWith(navigate(req)); return; }

  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(function (hit) {
      if (hit) {
        // Refresh in the background so the next launch has the new build.
        fetch(req).then(function (res) { store(req, res); }).catch(function () {});
        return hit;
      }
      return fetch(req)
        .then(function (res) { store(req, res); return res; })
        .catch(function () { return cachedPage(req); });
    })
  );
});
